# Generated by Django 3.0.8 on 2020-07-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='fellowship',
        ),
    ]
