# Generated by Django 3.0.8 on 2020-07-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatmember',
            name='turn_state',
            field=models.BooleanField(default=False),
        ),
    ]
