# Generated by Django 3.0.8 on 2020-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_combatmember_turn_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatinstance',
            name='combat_state',
            field=models.BooleanField(default=False),
        ),
    ]
