# Generated by Django 3.0.8 on 2020-07-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesheet',
            name='base',
        ),
        migrations.RemoveField(
            model_name='gamesheet',
            name='game',
        ),
        migrations.AlterField(
            model_name='combatmember',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='combat.CombatInstance'),
        ),
        migrations.DeleteModel(
            name='GameInstance',
        ),
        migrations.DeleteModel(
            name='GameSheet',
        ),
    ]
